"use strict";
// Seven visual themes for generated decks. Colors are hex without '#'.
// `glass` / `glassBorder` drive the glassmorphism card simulation in the pptx.

const THEMES = {
  "midnight-glass": {
    name: "Midnight Glass",
    nameMy: "မှန်ချပ် နက်ပြာ",
    bg: "070D1A",
    bgDeep: "04070F",
    band: "12233D",
    accent: "5EB1FF",
    accentSoft: "A8D4FF",
    title: "FFFFFF",
    text: "E5E7EB",
    muted: "8CA3C4",
    footer: "54687F",
    glass: "FFFFFF",
    glassBorder: "2E435F",
  },
  "navy-gold": {
    name: "Navy Gold",
    nameMy: "နက်ပြာ + ရွှေ",
    bg: "0E1A33",
    bgDeep: "0A1328",
    band: "16264D",
    accent: "D4AF37",
    accentSoft: "F3D97B",
    title: "FFFFFF",
    text: "E5E7EB",
    muted: "9AA3B8",
    footer: "5B6B8C",
    glass: "FFFFFF",
    glassBorder: "2C3D5E",
  },
  "minimal": {
    name: "Modern Minimal",
    nameMy: "ရိုးရှင်း",
    bg: "FFFFFF",
    bgDeep: "F4F5F7",
    band: "EFF1F4",
    accent: "2563EB",
    accentSoft: "93B4F5",
    title: "1E3A8A",
    text: "374151",
    muted: "6B7280",
    footer: "9CA3AF",
    glass: "FFFFFF",
    glassBorder: "D8DEE8",
  },
  "impact": {
    name: "Bold Impact",
    nameMy: "တောက်ပ",
    bg: "0B0B10",
    bgDeep: "050508",
    band: "1A1A22",
    accent: "FF3D5A",
    accentSoft: "FF8FA3",
    title: "FFFFFF",
    text: "E5E7EB",
    muted: "8E93A6",
    footer: "555A70",
    glass: "FFFFFF",
    glassBorder: "2E2E3A",
  },
  "corporate": {
    name: "Corporate Blue",
    nameMy: "ကော်ပိုရိတ်",
    bg: "0C2E5C",
    bgDeep: "082040",
    band: "14407E",
    accent: "4FC3F7",
    accentSoft: "A9E3FC",
    title: "FFFFFF",
    text: "E5E7EB",
    muted: "9DB8D9",
    footer: "5E7FA6",
    glass: "FFFFFF",
    glassBorder: "2A5A94",
  },
  "myanmar": {
    name: "Myanmar Royal",
    nameMy: "မြန်မာ ရိုးရာ",
    bg: "5E0D0D",
    bgDeep: "420808",
    band: "7A1414",
    accent: "F5C542",
    accentSoft: "F9DC8A",
    title: "FFFFFF",
    text: "E5E7EB",
    muted: "D9B98A",
    footer: "A67C52",
    glass: "FFFFFF",
    glassBorder: "8A2A2A",
  },
  "violet": {
    name: "Violet Tech",
    nameMy: "ခရမ်း နည်းပညာ",
    bg: "1A1033",
    bgDeep: "120B24",
    band: "2A1B52",
    accent: "8B5CF6",
    accentSoft: "C4B0FA",
    title: "FFFFFF",
    text: "E5E7EB",
    muted: "A89CCF",
    footer: "6E6396",
    glass: "FFFFFF",
    glassBorder: "3D2C66",
  },
};

const THEME_KEYS = Object.keys(THEMES);

module.exports = { THEMES, THEME_KEYS };
